captainVersion: 4
services:
    $$cap_appname:
        image: hellogpt/hellogpt:$$cap_pod_dango
        env_file:
            - $$cap_appname_env_file
        volumes:
            - $$cap_appname-data:/data
        restart: always
        caproverExtra:
            containerHttpPort: '8000'

caproverOneClickApp:
    variables:
        - id: $$cap_pod_danjo
          label: HelloGPT Pod Version
          defaultValue: latest
          description: The version of the HelloGPT Docker image to use.
          validRegex: /^([^\s^\/])+$/
        - id: $$cap_appname_env_file
          label: Environment File
          defaultValue: .env
          description: Path to the environment variables file.
          validRegex: /.+/
    instructions:
        start: >-
            HelloGPT is a Django application that provides various AI services.
        end: >-
            Please wait for a few minutes. HelloGPT is deployed and available as $$cap_appname.
    displayName: HelloGPT
    isOfficial: true
    description: HelloGPT is a Django application providing AI services.
    documentation: https://github.com/yourusername/hellogpt
